Orobinsk/secret_project

config/build/buildPlugins.ts, src/api/api.ts, src/api/apiTypes.ts, src/components/App.tsx, src/constants.ts
Откорректировал запрос movie и добавил типизацию. Отключил плагин с отдельной проверкой типов, потому что он почему-то только замедлял.
=> fix getMovie api

.vscode/settings.json, eslint.config.mjs, src/api/api.ts, src/components/App.tsx, src/components/carousel/Carousel.tsx, src/components/movieList/MovieItem.tsx, src/pages/MainPage/MainPage.tsx
исправил пропсы в компоненте movieList. В проекте используется не типичный файл настроек eslint, поэтому закинул setting.json для проекта. исправил другие мелкие баги и удалил ненужное
=> hot fix movieList props

src/providers/router/Router.tsx
теперь путь "/" сразу ведет на main page
=> fix index route

src/components/carousel/Carousel.tsx, src/components/movieItem/MovieItem.tsx, src/layouts/Root.tsx, src/providers/theme/theme.ts
Добавил ThemeProvider, основную цветовую палитру, вынес классы и немного отрефакторил [MovieItem.tsx](https://github.com/Orobinsk/secret_project/compare/aor-add-theme-provider?expand=1#diff-54080e3b9245f42e2980dcfdda3b1f8c8e89b6e8b6969979e278810558a0591e).
Предлагаю в дальнейшем, если стилей не много и они не используются в других файлах, выносить их в константу styles, как это сделано в [MovieItem.tsx](https://github.com/Orobinsk/secret_project/compare/aor-add-theme-provider?expand=1#diff-54080e3b9245f42e2980dcfdda3b1f8c8e89b6e8b6969979e278810558a0591e). В противном случае рекомендуется создавать файл CSS Module
=> add theme provider

jest.config.ts, package-lock.json, package.json, setupTests.ts
добавил библиотеку jest-dom чтобы использовать основные матчеры из Jest
=> fix react testing library

src/components/carousel/Carousel.test.tsx, src/components/carousel/Carousel.tsx
=> did a carousel test

.husky/pre-commit, .husky/pre-push, .prettierrc, lint-staged.config.mjs, package-lock.json, package.json, src/pages/FilmPage/components/BackgroundPoster.tsx
добавил husky и lint-staged. Теперь при коммите происходит проверка на ошибки ts,eslint,prietter. Если находит ошибку то отображает ее в консоли. При push запускаюся все тесты `npm test`
=> Aor add husky

src/components/App.tsx, src/components/carousel/Carousel.tsx, src/components/carousel/createCarouselStyles.ts
починила адаптив для маленьких экранов
=> fix carousel adaptiv

src/components/PageError/PageError.tsx, src/layouts/Root.tsx, src/providers/ErrorBoundary/ErrorBoundary.tsx, src/providers/theme/theme.ts
Добавил error boundary.  Добавил в палетку 3 основные цвета
Теперь если приложение падает показываем такую ошибку:
=> add error boundary

src/api/apiTypes/apiListsTypes.ts, src/api/apiTypes/apiTypes.ts, src/assets/noimg.svg, src/components/ReleaseCalend/ReleaseCalendar.tsx, src/components/ReleaseCalend/createReleaseCalendarStyles.ts, src/constants.ts, src/pages/MainPage/MainPage.tsx
=> i made calendar

src/components/carousel/Carousel.tsx, src/components/carousel/createCarouselStyles.ts
добавил скелетон в карусель и немного поправил css
=> add skeleton to carousel

src/UIKit/PosterModal/PosterModal.tsx, src/UIKit/PosterModal/modalStyles.ts
подправил адаптивность постера. теперь на мобильных показываем на весь экран.
=> fix poster adaptivity

src/UIKit/FilterButton/FilterButton.tsx, src/api/api.ts, src/api/apiTypes/apiGenresTypes.ts, src/components/carousel/Carousel.tsx, src/constants.ts, src/pages/ListOfMovies/DropDownMenu/DropDownMenu.tsx, src/pages/ListOfMovies/ListOfMovies.tsx, src/pages/ListOfMovies/createListOfMoviesStyles.ts, src/providers/router/Router.tsx
сделал страницу со списком фильмов и разными фильтрами
=> add list of movies page

src/api/apiTypes/apiTypes.ts, src/components/MovieTrailer/MovieTrailer.tsx, src/components/posterCard/PosterCard.tsx, src/constants.ts, src/pages/FilmPage/FilmPage.tsx, src/pages/FilmPage/components/MovieTrailerModal/MovieTrailerModal.tsx, src/pages/FilmPage/components/MovieTrailerModal/movieTrailerModalStyles.ts, src/pages/FilmPage/createFilmPageStyles.ts, src/styles.scss, src/types/movieTypes.ts
добавил возможность просматривать трейлеры фильма на странице фильма. Также добавил `box-sizing: border-box` на все приложение
=> add trailers

config/build/buildWebpackConfig.ts, src/api/apiTypes/apiTypes.ts, src/components/ReleaseCalend/ReleaseCalendar.tsx, src/index.tsx, src/pages/FilmPage/FilmPage.tsx, src/pages/FilmPage/components/MovieDesc.tsx, src/pages/FilmPage/components/MovieReviews.tsx, src/pages/ListOfMovies/DropDownMenu/DropDownMenu.tsx, src/pages/ListOfMovies/ListOfMovies.tsx, src/pages/SearchResult/SearchResult.tsx, tsconfig.json
- Включил Strict Mode в TypeScript. Теперь TS предупреждает о большем количестве потенциальных ошибок. 
- Обернул приложение в `<StrictMode />`. Это вызывает двойной рендеринг в режиме разработки, а также другие изменения, что помогает выявлять дополнительные проблемы и ошибки. Следует отметить, что теперь `useEffect` вызывается дважды из-за двойного рендера, поэтому **запросы выполняются дважды. Это ожидаемое поведение**.
=> enable strict mods

src/UIKit/PosterModal/PosterModal.tsx, src/api/api.ts, src/api/apiTypes/apiPersonTypes.ts, src/pages/ActorsPage/ActorsPage.tsx, src/pages/ActorsPage/CreateActorsPageStyles.ts, src/pages/FilmPage/FilmPage.tsx, src/providers/router/Router.tsx, src/types/personTypes.ts
сделала страницу для актера - пока драфт, буду дополнять
=> add person page

src/api/api.ts, src/api/apiTypes/apiTypes.ts, src/constants.ts, src/pages/FilmPage/components/MovieReviews.tsx, src/types/movieTypes.ts
добавил пагинацию для комментариев фильма. к сожалению не проверил заранее и оказалось что комментариев обычно меньше 7 штук.
Внес изменения в типизацию getMovie. Теперь правильно типизируется.
=> pagination review

src/components/ReleaseCalend/ReleaseCalendar.tsx, src/components/ReleaseCalend/createReleaseCalendarStyles.ts
добавила скелетон для календаря релизов
=> added a skeleton to the calendar

src/pages/FilmPage/components/MovieReviews.tsx
исправил регрессию:
отображался 0 если отзывов нет
=> hot fix review

README.md, public/index.html, src/components/Player.tsx, src/components/carousel/Carousel.tsx, src/pages/FilmPage/FilmPage.tsx, src/pages/FilmPage/components/MovieDesc.tsx, src/pages/FilmPage/components/MovieReviews.tsx
- добавил скелетон на странице фильма
- добавил плеер
- убрал надписи more  и popular review для комментариев
- исправил в карусели кнопку “Popular film this weak”
=> Add a player and skeleton to the film page

jest.config.ts, src/components/App.tsx, src/fileMock.js, src/pages/ActorsPage/ActorsPage.tsx, src/pages/FilmPage/FilmPage.tsx, src/pages/ListOfMovies/ListOfMovies.tsx, src/pages/MainPage/MainPage.tsx, src/pages/SearchResult/SearchResult.tsx, src/pages/SearchResult/searchResultsStyles.ts, src/providers/router/Router.test.tsx
написала 🚬 смок-тест для проверки рендеринга страниц
=> Mb router test

src/pages/FilmPage/FilmPage.tsx, src/pages/FilmPage/createFilmPageStyles.ts
добавила кнопку "More" на странице фильма, которая появляется только в случае, если высота контента превышает 40 пикселей. Это позволяет скрывать лишние данные в случае переполнения и отображать их при клике на кнопку. Реализована возможность раскрытия/сокрытия контента с помощью кнопки с текстом "MORE"/"HIDE".
=> upd-ladels

src/components/MovieBox/MovieBox.tsx, src/pages/ActorsPage/ActorsPage.tsx, src/pages/ListOfMovies/ListOfMovies.tsx
Добавила компонент с отображением всех фильмов актера
=> new element

src/pages/ActorsPage/ActorsMovies.tsx, src/pages/ActorsPage/ActorsPage.tsx
убрал ненужные перерисовки страницы актера при переключении пагинации фильмов. 
Компонент ререндерился из-за того что изменялось состояние page. Сейчас я вынес это состояние, саму пагинацию и список фильмов в отдельный компонент.
=> actor page redraw fix
